{
  "uuid": "dee2407a-c8c3-4953-9715-a1e61de07e2e",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "87ca7c47-ad10-44db-873d-e8668f2e9be3"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1747276083635,
  "stop": 1747276103641
}