{
  "uuid": "10a01136-4d48-478e-81e8-4bb0597dc6ba",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "5fca0aae-e55b-4e9b-a108-148615b321b9"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1712297312919,
  "stop": 1712297318007
}