{
  "uuid": "6479a961-559b-41db-b5c1-9eb9f9530472",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "1455c5eb-cb9e-4a81-aab0-b71cef02f083"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1740538802638,
  "stop": 1740538824751
}