{
  "uuid": "69781d04-097a-4c69-bf4a-267ff8ae955e",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "f0ae2cd1-7984-4496-a2af-d715c16caeea"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1741889145938,
  "stop": 1741889160439
}