{
  "uuid": "03b183db-5e5a-481c-a722-5d52b246c104",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "b5ba065b-06e0-4471-8e8d-1efce8651f7c"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1761268905684,
  "stop": 1761268920856
}