{
  "uuid": "59bb7262-01b8-4628-9762-76f4f9217151",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "45faedb3-ec34-4933-9f6e-da83d4d659bc"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1727072377862,
  "stop": 1727072384422
}