{
  "uuid": "5a5d7254-7719-4b4a-92be-fc2b1d2a33d1",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "fafc5df8-c940-4154-910a-f4db36aa6f2a"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1717466980595,
  "stop": 1717466988885
}