{
  "uuid": "9dc79d1f-8d31-480b-81b1-1e49375a25db",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "061f3e28-a041-48be-9fa3-ec0ded581be5"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1721711444981,
  "stop": 1721711449843
}