{
  "uuid": "eab95fef-3e63-4b7c-9555-5e56f52124fd",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "a57c8f04-3fde-4c62-ada6-3b5d06cac403"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1706583315816,
  "stop": 1706583320504
}