{
  "uuid": "596bc6ce-b7b0-4506-b4b3-69c37972669a",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "34a07e7b-e852-478b-a33a-9142a5302a58"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1706591364526,
  "stop": 1706591371596
}