{
  "uuid": "d9db11b0-005f-4010-9c02-11a516361265",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "31dbcdf7-2793-47d3-8f5c-312e181bcc9a"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1725342500908,
  "stop": 1725342509407
}