{
  "uuid": "d1547496-305a-4f2a-8d26-88b6e571ec4f",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "9e80b4d1-9143-4c5e-b1a0-a0943639c7e1"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1717573559475,
  "stop": 1717573564506
}