{
  "uuid": "c47d381e-107b-408e-a0d5-a806ffc12ddd",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "b74b68e8-3ab6-4479-837b-3842b1a8708c"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1707980370402,
  "stop": 1707980374706
}