{
  "uuid": "e3a99603-232c-4dd1-b518-e7fb1812a168",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "0e611762-1b48-4590-8383-5a33dd55f3f2"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1727313991829,
  "stop": 1727313997355
}