{
  "uuid": "fb84d627-1332-46c1-a38e-078b7edf4a4a",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "0c87ca35-c85d-44ff-8472-ca0dcebf61c9"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1706585717846,
  "stop": 1706585724207
}