{
  "uuid": "d0fe68aa-e27a-4bb7-b2d3-8f6360601d95",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "ba6f7148-d93b-4403-a88f-272cd671ac76"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1716870907539,
  "stop": 1716870914680
}