{
  "uuid": "b366127a-2b16-4760-91a1-00b1cf0033b6",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "d851fc66-b9c9-46e1-a62b-9a4f0103fdec"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1717740849204,
  "stop": 1717740855354
}