{
  "uuid": "307ffe30-c5b6-4d9f-9017-c8d8d3a68030",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "aac32420-1539-4a29-9cb6-1f183dcf4aee"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1708583128895,
  "stop": 1708583132995
}