{
  "uuid": "0a7d4dfd-ec3d-4f57-9a7f-4bf25468a0c5",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "b7ce0f57-dc4c-4d0e-a685-33bbbe6aec22"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1706246190729,
  "stop": 1706246195568
}