{
  "uuid": "0045e2d5-44fb-4f9e-b422-1d1e454103c2",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "0c3baf8d-3cf8-4f6d-a380-153988f216f8"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1723178149464,
  "stop": 1723178155007
}