{
  "uuid": "6e14e315-d5f6-4723-8be0-9ca00837722b",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "aa9bc313-a172-46a3-b401-2728c7d5491e"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1716366845294,
  "stop": 1716366850890
}