{
  "uuid": "5ee4d98c-4388-4822-b7e4-5203213b94c8",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "51cb5f89-8910-4fdb-91dd-a73a4f5bdc9e"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1707799524155,
  "stop": 1707799530714
}