{
  "uuid": "50142454-901a-41fb-9d09-3b776d956f33",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "4ef16669-f0b1-4110-b8c1-92526bd3c8c3"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1717464897079,
  "stop": 1717464902706
}