{
  "uuid": "c2dafdd3-456d-40db-a1e1-f6981a9b5584",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "4cbe2547-7eec-4091-bf24-4e33c175b94c"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1728625716390,
  "stop": 1728625722627
}