{
  "uuid": "268f8ba0-e859-4535-9ba3-64a34354a151",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "e1a1bb33-095a-4c5f-b2db-4aa5b3cba648"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1713765019076,
  "stop": 1713765023692
}